import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar/NavBar";

export const metadata: Metadata = {
  title: "Holly Jordan Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main>
          <div className="page">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
